### ISSUE TITLE
MyriadPro small caps fontshape undefined

### ISSUE THREAD

**Issue by unidesign** [sebschub/FontPro#43]
Today I faced a problem when trying to use Small Caps with MyriadPro.
I built the font using `makeall --novietnamese --noligatures --wide-spacing`. I would assume since I didn't touched the `--*smallcaps` option that they were built. But when trying to compile the following MWE
```
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[lf]{MyriadPro}
\begin{document}
\sffamily
\textsc{SMALL caps Test}
\end{document}
```
using `pdflatex` it warns: `LaTeX Font Warning: Font shape OT1/MyriadPro-LF/m/sc undefined`.
I also tried other encodings like `LY1`, `T1` but the same happens...

Note: I tried Small Caps with `MinionPro` and they work flawless. Does MyriadPro has SC?

**Comment by sebschub** [comment]
Unfortunately, the Myriad Pro fonts just do not offer small caps. Nothing I could do.

**Comment by unidesign** [comment]
Thanks didn't expected that, would it be easy to supply faked small caps?

**Comment by sebschub** [comment]
Well, I've found [this](http://tex.stackexchange.com/questions/142247/improved-fake-small-caps) but I don't want to include in the package. There are other ways, with for example fontforge I think, but I've never tried.

**Comment by unidesign** [comment]
Thanks, I can understand. I will than just redefine `textsc` to use always `textsc\rmfamily #1`.
