### ISSUE TITLE
Errors compiling with otf fonts from Adobe Acroread but works with fonts from Adbobe Font Folio 11

### ISSUE THREAD

**Issue by spmp** [sebschub/FontPro#44]
Can you please adds some information in the Readme.md as to what fonts are supported.
It would be great to have an option to use FontPro with the readily available fonts from acroread.

**Comment by sebschub** [comment]
What is the problem? Acroread's font should work.

**Comment by spmp** [comment]
Errors of the nature already in the issues, namely not finding the Integral
fonts etc.
 will run it again for you and post the output on pastebin if you like.

Note that I am getting the fonts from the Acroread 9 debian package.

**Comment by sebschub** [comment]
Which issue do you refer to? Yes, please post more information.

**Comment by spmp** [comment]
OK, thats freakishly weird!
 I got a fresh copy from git and started all nice and Vanilla and... it
worked just fine.

Sorry to have wasted your time as its all good now for some unknown reason.
It may be that I had to add a package `fontware' from texlive along the
way...

anyway feeling stupid.

Thanks for the quick response all the same, and thanks for the scripts!

Jasper

**Comment by sebschub** [comment]
Don't worry, thanks for using this package.
