### ISSUE TITLE
Install script default directory can misbehave

### ISSUE THREAD

**Issue by ruud-v-a** [sebschub/FontPro#46]
The default install directory determined by `kpsewhich -expand-var='$TEXMFLOCAL'` can install at an undesired location: when I run `kpsewhich -expand-var='$TEXMFLOCAL'` (on Arch Linux with TeX Live 2014), the output is `/usr/local/share/texmf:/usr/share/texmf`. Note the two paths separated by a colon. The script will install into a directory literally containing this colon.

**Comment by sebschub** [comment]
Thanks for the warning. Actually, I was not aware that more than one folder was a valid value for `TEXMFLOCAL`. I do not want to parse for any strange values so I just added a question in  9956f4c58421283061eba1867debc369b9b97672 asking whether the folder is fine.

**Comment by ruud-v-a** [comment]
That seems like a fine solution to me, great!
