### ISSUE TITLE
Lots of rounding messages (MacTeX 2015)

### ISSUE THREAD

**Issue by sven-strothoff** [sebschub/FontPro#48]
I have used FontPro several times before and never encountered any problems. I am currently setting up my TeX environment on a new computer. I am now using the newly released MacTeX 2015.

When I try to build a font (tested with MinionPro and MyriadPro) I get lots of messages about rounding heights/depths. Building the font takes a really long time. ~~Although the script does not show any _error_ message after creating the font and installation works, the resulting font is unusable. Errors range from "unable to create bitmap fonts" to "font is not scalable" depending on where/how the fonts are used (I can provide more details if necessary).~~

My best guess is that this is related to the 2015 release of TeXLive/MacTex. The same version of the FontPro scripts using the same source font files works flawlessly on my old machine running MacTex 2014.

I attached the beginning of the output below. The messages at the end simply repeat thousands of times.

Please let me know if you need more information or if there is anything I can do to help track down or resolve this issue.

```
$ ./scripts/makeall MinionPro
Chosen font family is MinionPro
Different font versions found: --pack option is disabled
Creating PostScript fonts ...
Creating TeX metrics ...
Processing font MinionPro-Regular ... lf-t1,I had to round some heights by  units.
I had to round some depths by  units.
0.01650050.0045004I had to round some heights by  units.
I had to round some depths by  units.
0.01650050.0045004 lf-ot1,I had to round some heights by  units.
I had to round some depths by  units.
0.00750060.0020008I had to round some heights by  units.
I had to round some depths by  units.
0.00750060.0020008 lf-ly1,I had to round some heights by  units.
[...]
```

**Comment by haiboyu** [comment]
I have the same problem after upgrading to MacTeX2015.

**Comment by sven-strothoff** [comment]
As it turns out there were actually two issues instead of one. The unusable fonts were the result of an error in my setup, so I renamed the issue and removed that part from my original post.

So the resulting fonts seem to work fine.

After some digging into the code my best guess is that the `filtererr` script and the new version of the font tools in TeXLive 2015 don't match up, resulting in lots of error messages that would otherwise be filtered and collected.
As I am not sure which of the used tools emits these messages in the first place I was unable to figure our exactly what is going on.

**Comment by sebschub** [comment]
Thanks a lot, I'll try to reproduce the issue as soon as possible.

**Comment by arthurl** [comment]
@sven-strothoff It's an old issue, but can I ask how you resolved the "font is not scalable" problem? I'm experiencing the errors with Minion Pro:

pdflatex without microtype:

    (/usr/local/texlive/2016basic/texmf-local/tex/latex/MinionPro/MinionPro-FontDef
    .sty)) [1{/usr/local/texlive/2016basic/texmf-var/fonts/map/pdftex/updmap/pdftex
    .map}] [2]
    kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 0+525/600 --dpi 525 MinionPro-MediumItCapt-Base-ab
    mktexpk: don't know how to create bitmap font for MinionPro-MediumItCapt-Base-ab.
    mktexpk: perhaps MinionPro-MediumItCapt-Base-ab is missing from the map file.
    kpathsea: Appending font creation commands to missfont.log.
     )
    !pdfTeX error: pdflatex (file MinionPro-MediumItCapt-Base-ab): Font MinionPro-M
    ediumItCapt-Base-ab at 525 not found
     ==> Fatal error occurred, no output PDF file produced!
    
pdflatex with microtype:

    (/usr/local/texlive/2016basic/texmf-local/tex/latex/MinionPro/MinionPro-FontDef
    .sty)) [1{/usr/local/texlive/2016basic/texmf-var/fonts/map/pdftex/updmap/pdftex
    .map}
    ! pdfTeX error (font expansion): auto expansion is only possible with scalable 
    fonts.
    \AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                      \fi \fi 

Strangely enough, Cronos Pro and Myriad Pro are fine... I'm really not sure what to make of this.

FYI: This is BasicTeX 2016 on MacOS Sierra.

**Comment by sebschub** [comment]
@sven-strothoff @haiboyu Sorry for the wait. Can you still reproduce the error? If yes, which LCDF typetools version do you use? With version 2.105, I do not get the warnings.

**Comment by sven-strothoff** [comment]
I am not entirely sure what I was doing back then to be honest. So I will not be able to reproduce it. As I said above the problem was introduced in TexLive/MacTeX 2015. Some mismatch between a filter rule and the output of another tool.
Maybe it is fixed in newer TexLive releases. As you said it is working in an up-to-date version feel free to close this issue. If the issue still exists for someone it can be re-opened.

**Comment by sebschub** [comment]
Thanks for your answer. Please feel free to re-open if necessary.
