### ISSUE TITLE
Question on "keyval.tex"

### ISSUE THREAD

**Issue by starkshaw** [sebschub/FontPro#51]
I compiled this package with Minion Pro, but when I use it with Texpad, it pops out "KeyVal does not exist" and ask to create one, thus there will be an empty file named `keyval.tex` under the directory as same as the original `.tex` document. How can I solve this? Even there is no other visible issue.

This is how I include the package: `\usepackage[onlymath, minionint, lf]{MinionPro}`

**Comment by sebschub** [comment]
I suppose you don't have the keyval package installed. Which LaTeX distribution do you use?

**Comment by starkshaw** [comment]
XeLaTex.

**Comment by sebschub** [comment]
Sorry for the wait. XeLaTeX is not the distribution; instead it is something like TeXlive, MikteX, etc... Here you have to install the keyval package. If this is done, `kpsewhich keyval.sty` should give you something like `/usr/share/texmf/tex/latex/graphics/keyval.sty`.
